# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo",
#     "matplotlib==3.10.6",
#     "missingno==0.5.2",
#     "pandas==2.3.2",
#     "polars==1.32.3",
#     "requests==2.32.5",
# ]
# ///

import marimo

__generated_with = "0.15.1"
app = marimo.App(auto_download=["html"])


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Open Government Data, provided by **Statistisches Amt des Kantons Basel-Stadt - DCC Data Competence Center**
    *Autogenerated Python starter code for dataset with identifier* **100097**
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## Dataset
    # **Geschwindigkeitsmonitoring: Einzelmessungen**
    **Description**: <p></p><p></p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Einzelmessungen des
Geschwindigkeitsmonitorings der Kantonspolizei Basel-Stadt</p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Bei den dargestellten
Daten handelt es sich ausschliesslich um statistische Erhebungen. Diese stehen
nicht in einem Zusammenhang mit Ordnungsbussen oder einer strafrechtlichen
Verfolgung. Die statistischen Geschwindigkeitsmessungen dienen der Kantonspolizei
Basel-Stadt zur Überprüfung der Geschwindigkeit sowie der Verkehrssicherheit
(z.B. Sicherheit an Fussgängerstreifen) an der betreffenden Örtlichkeit. Die
Ergebnisse dienen zur Entscheidung, an welchen Örtlichkeiten Handlungsbedarf in
Form von Geschwindigkeitskontrollen besteht. Jedes Statistikgerät besitzt eine
einzige Punktgeometrie und ist meist mit zwei Richtungen versehen (Richtung 1
und 2).<o:p></o:p></p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Hinweis: Die
Messungen sind nicht zwingend repräsentativ für das ganze Jahr und müssen im
Kontext des Erhebungsdatums betrachtet werden. Darüber hinaus wurden gewisse
Messungen während einer ausserordentlichen Verkehrsführung (z.B.
Umleitungsverkehr infolge von Baustellentätigkeiten etc.) erhoben.
Manipulationen an Geräten können zu fehlerhaften Messungen führen.<o:p></o:p></p><p>


</p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><font face="Arial, sans-serif">Eine Übersicht aller Datensätze auf dem kantonalen Datenportal zum Geschwindigkeitsmonitoring sind unter </font><a href="https://data.bs.ch/explore/?refine.tags=Geschwindigkeitsmonitoring" target="_blank">https://data.bs.ch/explore/?refine.tags=Geschwindigkeitsmonitoring</a><font face="Arial, sans-serif"> aufrufbar.</font></p>Aus Kostengründen sind nur die Werte des aktuellen Jahres und des letzten Jahres als Tabelle / Visualisierung sichtbar.<p></p><p>Eine Vorschau aller Daten ist hier zu finden: <a href="https://datatools.bs.ch/Geschwindigkeitsmonitoring" target="_blank">https://datatools.bs.ch/Geschwindigkeitsmonitoring</a>.<br>Aufgrund der grossen Datenmenge kann es vorkommen, dass der Datensatz nicht vollständig heruntergeladen werden kann. Falls dieses Problem auftritt, kann man den vollständigen Datensatz und die Einzelmessungen der Messstationen hier herunterladen:</p><p></p><p></p><ul><li>vollständiger Datensatz (Achtung grösser als 10 GB): <a href="https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/all_data/geschwindigkeitsmonitoring_data.csv">https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/all_data/geschwindigkeitsmonitoring_data.csv</a></li><li>Einzelmessungen der Messstationen: <a href="https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/data/">https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/data/</a></li></ul><p>Die Mess-Standorte werden auch auf dem Geoportal Basel-Stadt publiziert: <a href="https://www.geo.bs.ch/geschwindigkeitsmonitoring" target="_blank">https://www.geo.bs.ch/geschwindigkeitsmonitoring</a></p><p></p>

    *You can find the dataset [under this link](https://data.bs.ch/explore/dataset/100097)*.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Metadata

    - **Dataset_identifier** `100097`
- **Title** `Geschwindigkeitsmonitoring: Einzelmessungen`
- **Description** `<p></p><p></p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Einzelmessungen des
Geschwindigkeitsmonitorings der Kantonspolizei Basel-Stadt</p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Bei den dargestellten
Daten handelt es sich ausschliesslich um statistische Erhebungen. Diese stehen
nicht in einem Zusammenhang mit Ordnungsbussen oder einer strafrechtlichen
Verfolgung. Die statistischen Geschwindigkeitsmessungen dienen der Kantonspolizei
Basel-Stadt zur Überprüfung der Geschwindigkeit sowie der Verkehrssicherheit
(z.B. Sicherheit an Fussgängerstreifen) an der betreffenden Örtlichkeit. Die
Ergebnisse dienen zur Entscheidung, an welchen Örtlichkeiten Handlungsbedarf in
Form von Geschwindigkeitskontrollen besteht. Jedes Statistikgerät besitzt eine
einzige Punktgeometrie und ist meist mit zwei Richtungen versehen (Richtung 1
und 2).<o:p></o:p></p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Hinweis: Die
Messungen sind nicht zwingend repräsentativ für das ganze Jahr und müssen im
Kontext des Erhebungsdatums betrachtet werden. Darüber hinaus wurden gewisse
Messungen während einer ausserordentlichen Verkehrsführung (z.B.
Umleitungsverkehr infolge von Baustellentätigkeiten etc.) erhoben.
Manipulationen an Geräten können zu fehlerhaften Messungen führen.<o:p></o:p></p><p>


</p><p class="MsoNormal" style="margin-bottom: 12pt; line-height: normal; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><font face="Arial, sans-serif">Eine Übersicht aller Datensätze auf dem kantonalen Datenportal zum Geschwindigkeitsmonitoring sind unter </font><a href="https://data.bs.ch/explore/?refine.tags=Geschwindigkeitsmonitoring" target="_blank">https://data.bs.ch/explore/?refine.tags=Geschwindigkeitsmonitoring</a><font face="Arial, sans-serif"> aufrufbar.</font></p>Aus Kostengründen sind nur die Werte des aktuellen Jahres und des letzten Jahres als Tabelle / Visualisierung sichtbar.<p></p><p>Eine Vorschau aller Daten ist hier zu finden: <a href="https://datatools.bs.ch/Geschwindigkeitsmonitoring" target="_blank">https://datatools.bs.ch/Geschwindigkeitsmonitoring</a>.<br>Aufgrund der grossen Datenmenge kann es vorkommen, dass der Datensatz nicht vollständig heruntergeladen werden kann. Falls dieses Problem auftritt, kann man den vollständigen Datensatz und die Einzelmessungen der Messstationen hier herunterladen:</p><p></p><p></p><ul><li>vollständiger Datensatz (Achtung grösser als 10 GB): <a href="https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/all_data/geschwindigkeitsmonitoring_data.csv">https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/all_data/geschwindigkeitsmonitoring_data.csv</a></li><li>Einzelmessungen der Messstationen: <a href="https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/data/">https://data-bs.ch/stata/kapo/geschwindigkeitsmonitoring/data/</a></li></ul><p>Die Mess-Standorte werden auch auf dem Geoportal Basel-Stadt publiziert: <a href="https://www.geo.bs.ch/geschwindigkeitsmonitoring" target="_blank">https://www.geo.bs.ch/geschwindigkeitsmonitoring</a></p><p></p>`
- **Contact_name** `Open Data Basel-Stadt`
- **Issued** `2021-02-02`
- **Modified** `2025-09-23T02:58:05+00:00`
- **Rights** `NonCommercialAllowed-CommercialAllowed-ReferenceRequired`
- **Temporal_coverage_start_date** `2024-01-14T23:00:00+00:00`
- **Temporal_coverage_end_date** `2025-09-14T22:00:00+00:00`
- **Themes** `['Mobilität und Verkehr']`
- **Keywords** `['Geschwindigkeit', 'Verkehr', 'Auto', 'PW', 'PKW', 'LW', 'LKW', 'Messwert', 'Einzelmessung', 'Messung']`
- **Publisher** `Kantonspolizei`
- **Reference** `None`


    ///
    """
    )
    return


@app.cell
def _():
    import os
    import pandas as pd
    import requests
    import matplotlib.pyplot as plt
    return os, pd, plt, requests


@app.cell
def _(plt):
    plt.style.use("ggplot")

    params = {
        "text.color": (0.25, 0.25, 0.25),
        "figure.figsize": [18, 6],
    }

    plt.rcParams.update(params)
    return


@app.cell
def _(os, pd, requests):
    def get_dataset(dataset_id):
        url=f"https://data.bs.ch/explore/dataset/{dataset_id}/download"
        r = requests.get(
            url, 
            params={
                "format": "csv", 
                "timezone": "Europe%2FZurich"
            }
        )
        data_path = os.path.join(os.getcwd(), "..", "data")
        if not os.path.exists(data_path):
            os.makedirs(data_path)
        csv_path = os.path.join(data_path, f"{dataset_id}.csv")
        with open(csv_path, "wb") as f:
            f.write(r.content)
        data = pd.read_csv(
            url, sep=";", on_bad_lines="warn", encoding_errors="ignore", low_memory=False
        )
        # if dataframe only has one column or less the data is not ";" separated
        if data.shape[1] <= 1:
            print(
                "The data wasn't imported properly. Very likely the correct separator couldn't be found.\nPlease check the dataset manually and adjust the code."
            )
        return data
    return (get_dataset,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Load data""")
    return


@app.cell
def _(get_dataset):
    # Read the dataset
    df = get_dataset(dataset_id="100097")
    df
    return (df,)


@app.cell
def _(mo):
    mo.md(r"""## Analyze Data""")
    return


@app.cell
def _(df):
    # check missing values with missingno
    # https://github.com/ResidentMario/missingno
    import missingno as msno

    msno.matrix(df, labels=True, sort="descending")
    return


@app.cell
def _(df):
    df.info(memory_usage="deep", verbose=True)
    return


@app.cell
def _(df, pd, plt):
    # plot a histogram for each numerical feature
    try:
        df.hist(bins=25, rwidth=0.9)
        plt.tight_layout()
        plt.show()
    except pd.errors.DataError:
        print("No numerical data to plot.")
    return

@app.cell
def _(mo):
    mo.md(r"""**Questions about the data?** Open Data Basel-Stadt | opendata@bs.ch""")
    return

if __name__ == "__main__":
    app.run()
