# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo",
#     "matplotlib==3.10.6",
#     "missingno==0.5.2",
#     "pandas==2.3.2",
#     "polars==1.32.3",
#     "requests==2.32.5",
# ]
# ///

import marimo

__generated_with = "0.15.1"
app = marimo.App(auto_download=["html"])


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Open Government Data, provided by **Statistisches Amt des Kantons Basel-Stadt - DCC Data Competence Center**
    *Autogenerated Python starter code for dataset with identifier* **100175**
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Dataset
    # **Smarte Strasse: Geschwindigkeitsmessungen**
    **Description**: <p>Der Datensatz zeigt Geschwindigkeit und Lautstärke von Fahrzeugen mit der dazugehörigen Zeitangabe. Aus Datenschutzgründen werden jeweils Gruppen von 20 Fahrzeugen gebildet, die Reihenfolge randomisiert, und nur nur jeweils Start- und Endzeitpunkt des jeweiligen Zeitintervalls angegeben. </p><p><b>Wichtig:</b> Die Geschwindigkeits-Werte vor dem 25.03.2022 um 11:35 Uhr sind nicht kalibriert. Je nach Fahrspur werden diese Werte daher um bis zu 40% zu tief angegeben. </p><p class="" style="font-family: sans-serif;"><b>Weitere Informationen und Daten rund um das Projekt «Smarte Strasse» finden Sie unter den folgenden Links:</b></p><ul><li>Weitere Informationen zum Projekt «Smarte Strasse»: <a href="https://www.bs.ch/medienmitteilungen/pd/2022-pilotprojekt-smarte-strasse-neue-technologien-im-test-fuer-die-stadt-von-morgen" target="_blank">https://www.bs.ch/medienmitteilungen/pd/2022-pilotprojekt-smarte-strasse-neue-technologien-im-test-fuer-die-stadt-von-morgen</a> </li><li>Genaue Standorte aller Sensoren: <a href="https://data.bs.ch/explore/dataset/100114/" target="_blank">https://data.bs.ch/explore/dataset/100114/</a> </li><li>Weitere Datensätze rund um das Thema «Smarte Strasse»: <a href="https://data.bs.ch/explore/?refine.tags=smarte+strasse" target="_blank">https://data.bs.ch/explore/?refine.tags=smarte+strasse</a> </li></ul><p style="font-family: sans-serif;"><span style="font-weight: bolder;">Hinweis: Die Sensoren an der Gundeldingerstrasse wurden am 29.6.23 abmontiert. Es werden keine Daten mehr erhoben.</span></p><p style="font-family: sans-serif; margin-bottom: 1em;">Änderungsprotokoll:<br>29.06.2023 - Aktualisierungsintervall von "CONT" auf "NEVER" geändert.</p>

    *You can find the dataset [under this link](https://data.bs.ch/explore/dataset/100175)*.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Metadata

    - **Dataset_identifier** `100175`
- **Title** `Smarte Strasse: Geschwindigkeitsmessungen`
- **Description** `<p>Der Datensatz zeigt Geschwindigkeit und Lautstärke von Fahrzeugen mit der dazugehörigen Zeitangabe. Aus Datenschutzgründen werden jeweils Gruppen von 20 Fahrzeugen gebildet, die Reihenfolge randomisiert, und nur nur jeweils Start- und Endzeitpunkt des jeweiligen Zeitintervalls angegeben. </p><p><b>Wichtig:</b> Die Geschwindigkeits-Werte vor dem 25.03.2022 um 11:35 Uhr sind nicht kalibriert. Je nach Fahrspur werden diese Werte daher um bis zu 40% zu tief angegeben. </p><p class="" style="font-family: sans-serif;"><b>Weitere Informationen und Daten rund um das Projekt «Smarte Strasse» finden Sie unter den folgenden Links:</b></p><ul><li>Weitere Informationen zum Projekt «Smarte Strasse»: <a href="https://www.bs.ch/medienmitteilungen/pd/2022-pilotprojekt-smarte-strasse-neue-technologien-im-test-fuer-die-stadt-von-morgen" target="_blank">https://www.bs.ch/medienmitteilungen/pd/2022-pilotprojekt-smarte-strasse-neue-technologien-im-test-fuer-die-stadt-von-morgen</a> </li><li>Genaue Standorte aller Sensoren: <a href="https://data.bs.ch/explore/dataset/100114/" target="_blank">https://data.bs.ch/explore/dataset/100114/</a> </li><li>Weitere Datensätze rund um das Thema «Smarte Strasse»: <a href="https://data.bs.ch/explore/?refine.tags=smarte+strasse" target="_blank">https://data.bs.ch/explore/?refine.tags=smarte+strasse</a> </li></ul><p style="font-family: sans-serif;"><span style="font-weight: bolder;">Hinweis: Die Sensoren an der Gundeldingerstrasse wurden am 29.6.23 abmontiert. Es werden keine Daten mehr erhoben.</span></p><p style="font-family: sans-serif; margin-bottom: 1em;">Änderungsprotokoll:<br>29.06.2023 - Aktualisierungsintervall von "CONT" auf "NEVER" geändert.</p>`
- **Contact_name** `Open Data Basel-Stadt`
- **Issued** `2022-02-07`
- **Modified** `2024-03-01T08:00:31+00:00`
- **Rights** `NonCommercialAllowed-CommercialAllowed-ReferenceRequired`
- **Temporal_coverage_start_date** `2022-01-31T23:00:00+00:00`
- **Temporal_coverage_end_date** `2023-06-26T22:00:00+00:00`
- **Themes** `['Mobilität und Verkehr']`
- **Keywords** `['Smarte Strasse', 'Tempo', 'Lärm', 'Lautstärke', 'Auto']`
- **Publisher** `Amt für Umwelt und Energie`
- **Reference** `None`


    ///
    """
    )
    return


@app.cell
def _():
    import os
    import pandas as pd
    import requests
    import matplotlib.pyplot as plt
    return os, pd, plt, requests


@app.cell
def _(plt):
    plt.style.use("ggplot")

    params = {
        "text.color": (0.25, 0.25, 0.25),
        "figure.figsize": [18, 6],
    }

    plt.rcParams.update(params)
    return


@app.cell
def _(os, pd, requests):
    def get_dataset(dataset_id):
        url = f"https://data.bs.ch/api/explore/v2.1/catalog/datasets/{dataset_id}/exports/csv"
        r = requests.get(
            url, 
            params={
                "timezone": "Europe%2FZurich",
                "use_labels": "true"
            }
        )
        data_path = os.path.join(os.getcwd(), "..", "data")
        if not os.path.exists(data_path):
            os.makedirs(data_path)
        csv_path = os.path.join(data_path, f"{dataset_id}.csv")
        with open(csv_path, "wb") as f:
            f.write(r.content)
        data = pd.read_csv(
            url, sep=";", on_bad_lines="warn", encoding_errors="ignore", low_memory=False
        )
        # if dataframe only has one column or less the data is not ";" separated
        if data.shape[1] <= 1:
            print(
                "The data wasn't imported properly. Very likely the correct separator couldn't be found.\nPlease check the dataset manually and adjust the code."
            )
        return data
    return (get_dataset,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Load data""")
    return


@app.cell
def _(get_dataset):
    # Read the dataset
    df = get_dataset(dataset_id="100175")
    df
    return (df,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Analyze Data""")
    return


@app.cell
def _(df):
    # check missing values with missingno
    # https://github.com/ResidentMario/missingno
    import missingno as msno

    msno.matrix(df, labels=True, sort="descending")
    return


@app.cell
def _(df):
    df.info(memory_usage="deep", verbose=True)
    return


@app.cell
def _(df, pd, plt):
    # plot a histogram for each numerical feature
    try:
        df.hist(bins=25, rwidth=0.9)
        plt.tight_layout()
        plt.show()
    except ValueError:
        print("No numerical data to plot.")
    return

@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""**Questions about the data?** Open Data Basel-Stadt | opendata@bs.ch""")
    return

if __name__ == "__main__":
    app.run()
