# /// script
# # pandas' pd.to_datetime() segfaults under Python 3.14 (as of pandas 2.3.2) -- cap below it
# requires-python = ">=3.12,<3.14"
# dependencies = [
#     "marimo",
#     "folium==0.20.0",
#     "matplotlib==3.10.6",
#     "missingno==0.5.2",
#     "pandas==2.3.2",
#     "polars==1.32.3",
#     "requests==2.32.5",
# ]
# ///

import marimo

__generated_with = "0.15.1"
app = marimo.App(auto_download=["html"])


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Open Government Data, provided by **Statistisches Amt des Kantons Basel-Stadt - DCC Data Competence Center**
    *Autogenerated Python starter code for dataset with identifier* **100300**
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Dataset
    # **Resultate der Bürgergemeinderatswahlen 18. Juni 2023**
    **Description**: <p>Der vorliegende Datensatz beinhaltet Resultate der Bürgergemeinderatswahlen Basel vom 18. Juni 2023 auf Ebene der einzelnen Kandidierenden. Weitere Informationen zu den Wahlen sind hier zu finden: <a href="https://bgbasel.ch/de/politische-organe/buergergemeinderat/wahlen2023.html" target="_blank">https://bgbasel.ch/de/politische-organe/buergergemeinderat/wahlen2023.html</a><br></p>

    *You can find the dataset [under this link](https://data.bs.ch/explore/dataset/100300)*.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Metadata

- **Dataset_identifier** `100300`
- **Title** `Resultate der Bürgergemeinderatswahlen 18. Juni 2023`
- **Description** `<p>Der vorliegende Datensatz beinhaltet Resultate der Bürgergemeinderatswahlen Basel vom 18. Juni 2023 auf Ebene der einzelnen Kandidierenden. Weitere Informationen zu den Wahlen sind hier zu finden: <a href="https://bgbasel.ch/de/politische-organe/buergergemeinderat/wahlen2023.html" target="_blank">https://bgbasel.ch/de/politische-organe/buergergemeinderat/wahlen2023.html</a><br></p>`
- **Contact_name** `Open Data Basel-Stadt`
- **Issued** `2023-06-17`
- **Modified** `2025-04-28T07:47:13+00:00`
- **Rights** `NonCommercialAllowed-CommercialAllowed-ReferenceRequired`
- **Temporal_coverage_start_date** `None`
- **Temporal_coverage_end_date** `None`
- **Themes** `['Politik', 'Bevölkerung', 'Gesetzgebung']`
- **Keywords** `['Wahlen', 'Bürgergemeinderat']`
- **Creator** `Bürgergemeinde der Stadt Basel`
- **Reference** `None`


    ///
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Data dictionary

| Field | Type | Description |
| :-- | :-- | :-- |
| `wahlbezeichnung` | text | Titel der Wahl |
| `amtsdauer` | text | Anzahl Jahre, auf welche die Mitglieder gewählt werden |
| `wahltermin` | date | Datum der Wahl |
| `anzahl_sitze` | int | Anzahl Sitze, die für einen Wahlkreis zur Verfügung stehen |
| `wahlkreis_nr` | int | Nummer des Wahlkreises |
| `wahlkreis_code` | int | Code des Wahlkreises |
| `wahlkreisbezeichnung` | text | Name des Wahlkreises |
| `stimmberechtigte_manner` | int | Anzahl in einem Wahlkreis stimmberechtigter Männer |
| `stimmberechtigte_frauen` | int | Anzahl in einem Wahlkreis stimmberechtigter Frauen |
| `stimmberechtigte` | int | Anzahl Stimmberechtigter total in einem Wahlkreis |
| `stimmberechtigte_auslandschweizer` | int | Anzahl stimmberechtigter Auslandschweizer |
| `wahlzettel` | int | Anzahl Wahlzettel |
| `briefliche_stimmabgaben` | int | Anzahl brieflich eingelegter Wahlzettel |
| `ungultige_wahlzettel` | int | Anzahl ungültiger Wahlzettel |
| `leere_wahlzettel` | int | Anzahl leer eingelegter Wahlzettel |
| `unveranderte_wahlzettel` | int | Anzahl unveränderter Wahlzettel |
| `veranderte_wahlzettel_mit_bezeichnung` | int | Anzahl veränderter Wahlzettel mit Listenbezeichnung (leere Linien zählen als Parteistimmen) |
| `veranderte_wahlzettel_ohne_bezeichnung` | int | Anzahl veränderter Wahlzettel ohne Listenbezeichnung (leere Linien werden nicht gezählt) |
| `leere_stimmen` | int | Anzahl leerer Stimmen |
| `partei_id` | int | ID der Partei |
| `parteikurzbezeichnung` | text | Parteikurzbezeichnung |
| `parteibezeichnung` | text | Name der Partei |
| `anzahl_sitze_liste` | int | Anzahl Sitze einer Liste in einem Wahlkreis |
| `unveranderte_wahlzettel_liste` | int | Anzahl unveränderte Wahlzettel einer Liste in einem Wahlkreis |
| `veranderte_wahlzettel_liste` | int | Anzahl veränderte Wahlzettel einer Liste in einem Wahlkreis |
| `kandidatenstimmen_unveranderte_wahlzettel` | int | Anzahl Stimmen aller Kandidatinnen und Kandidaten einer Liste aus unveränderten Wahlzetteln |
| `zusatzstimmen_unveranderte_wahlzettel` | int | Anzahl Zusatzstimmen für alle Kandidatinnen und Kandidaten einer Liste aus unveränderten Wahlzetteln |
| `kandidatenstimmen_veranderte_wahlzettel` | int | Anzahl Stimmen für alle Kandidatinnen und Kandidaten einer Liste aus veränderten Wahlzetteln |
| `zusatzstimmen_veranderte_wahlzettel` | int | Anzahl Zusatzstimmen für alle Kandidatinnen und Kandidaten einer Liste aus veränderten Wahlzetteln |
| `kandidaten_nr` | text | Kandidaten-Nr |
| `kumulation` | text | K: eine Kandidatin oder ein Kandidat auf einem unveränderten Wahlzettel ist mehrfach aufgeführt. |
| `bisher` | text | Angabe, ob eine Kandidatin oder ein Kandidat in der abgelaufenen Legislatur im Parlament vertreten war oder nicht |
| `gewahlt` | text | Angabe, ob eine Kandidatin oder ein Kandidat gewählt ist |
| `ganzer_name` | text | Nachname und Vorname, mit Komma getrennt |
| `name` | text | Nachname |
| `vorname` | text | Vorname |
| `rangfolge` | int | Rangfolge innerhalb einer Liste gemäss Anzahl Stimmen (bei Stimmengleichheit entscheidet das Los). |
| `00_ohne` | int | Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer Liste ohne Bezeichnung |
| `01_fdp` | int | FDP. Die Liberalen Basel-Stadt und Jungfreisinnige; Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `03_ldp` | int | LDP Liberal-Demokratische Partei Basel-Stadt und Jungliberale; Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `04_evp` | int | Evangelische Volkspartei Basel-Stadt; Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `05_sp` | int | Sozialdemokratische Partei Basel-Stadt (SP) und JUSO; Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `07_mitte` | int | Die Mitte Basel-Stadt (MITTE); Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `10_glp` | int | Grünliberale Partei Basel-Stadt; Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `12_svp` | int | Schweizerische Volkspartei Basel-Stadt (SVP); Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `17_gp` | int | Grüne Partei (GP); Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `27_basta` | int | Basels starke Alternative (BastA!); Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `30_unabh` | int | Unabhängige (Unabh.); Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus einer veränderten Liste dieser Partei |
| `ungestempelte_wahlzettel` | int | Anzahl ungestempelter Wahlzettel |
| `listen_nr` | text | Listen-Nr |
| `stimmen_unveranderte_wahlzettel` | int | Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus unveränderten Wahlzetteln |
| `stimmen_veranderte_wahlzettel` | int | Anzahl Stimmen für eine Kandidatin oder einen Kandidaten aus veränderten Wahlzetteln |
| `stimmen_total_aus_wahlzettel` | int | Anzahl Stimmen total für eine Kandidatin oder einen Kandidaten |
| `total_der_gultigen_wahlzettel` | int | Total der gültigen Wahlzettel |
| `stimmbeteiligung` | geo_point_2d | Stimmbeteiligung: Berechnet als Anzahl Wahlzettel geteilt durch das Total der Stimmberechtigten |
| `anteil_brieflich_wahlende` | text | Anteil brieflich Wählende: Berechnet als Anzahl Briefliche Stimmabgaben geteilt durch das Anzahl Wahlzettel. |


    ///
    """
    )
    return


@app.cell
def _():
    import os
    import io
    import pandas as pd
    import requests
    import matplotlib.pyplot as plt
    return os, io, pd, plt, requests


@app.cell
def _(plt):
    plt.style.use("ggplot")

    params = {
        "text.color": (0.25, 0.25, 0.25),
        "figure.figsize": [18, 6],
    }

    plt.rcParams.update(params)
    return


@app.cell
def _(os):
    def ensure_data_dir() -> str:
        data_path = os.path.join(os.getcwd(), "..", "data")
        os.makedirs(data_path, exist_ok=True)
        return data_path
    return (ensure_data_dir,)


@app.cell
def _(io, pd, requests):
    def download_csv_page(
        session: requests.Session,
        dataset_id: str,
        limit: int,
        where: str | None = None,
    ) -> pd.DataFrame:
        # offset is always 0 here: the export endpoint only allows offset + limit
        # <= 10,000 for true pagination (likely an Elasticsearch deep-pagination
        # limit) and returns 400 Bad Request beyond that, but an offset=0 request
        # bypasses this and can return far larger result sets directly -- so
        # get_dataset uses `where` date-range filters instead of offset to split
        # large datasets, always fetching each slice from offset=0.
        base_url = "https://data.bs.ch/api/explore/v2.1"
        url = f"{base_url}/catalog/datasets/{dataset_id}/exports/csv"

        params = {
            "timezone": "Europe/Zurich",
            "use_labels": "false",
            "offset": 0,
            "limit": limit,
        }
        if where:
            params["where"] = where

        r = session.get(url, params=params)
        r.raise_for_status()

        buf = io.BytesIO(r.content)

        df = pd.read_csv(
            buf,
            sep=";",
            on_bad_lines="warn",
            encoding_errors="ignore",
            low_memory=False,
        )

        return df
    return (download_csv_page,)


@app.cell
def _(download_csv_page, ensure_data_dir, mo, os, pd, requests):
    def get_dataset(dataset_id: str, max_rows: int = 200_000) -> pd.DataFrame:
        """
        Download a dataset from data.bs.ch.

        Datasets up to max_rows rows are downloaded in full. This is starter
        code meant to get you exploring a dataset quickly, not a complete data
        pipeline -- some datasets in this catalogue have tens of millions of
        rows, far more than is practical (or useful) to pull into a notebook.
        For those, only a SAMPLE of max_rows rows is downloaded instead, spread
        evenly across the dataset's time range if it has a date/datetime field
        (so the sample isn't just the oldest or most recent slice), or just the
        first max_rows rows otherwise. A disclaimer is printed when this happens
        -- if you need the complete dataset, download it directly from the data
        shop link above instead.

        The result is written to ../data/{dataset_id}.csv and returned as a DataFrame.
        """
        base_url = "https://data.bs.ch/api/explore/v2.1"
        records_url = f"{base_url}/catalog/datasets/{dataset_id}/records"
        schema_url = f"{base_url}/catalog/datasets/{dataset_id}"

        session = requests.Session()
        common_params = {"timezone": "Europe/Zurich", "use_labels": "false"}

        r = session.get(records_url, params={**common_params, "limit": 1})
        r.raise_for_status()
        total_count = r.json().get("total_count", 0)
        if not isinstance(total_count, int) or total_count <= 0:
            total_count = 1

        data_path = ensure_data_dir()
        csv_path = os.path.join(data_path, f"{dataset_id}.csv")

        # full dataset fits comfortably in a single request
        if total_count <= max_rows:
            df = download_csv_page(session, dataset_id, limit=total_count)
            df.to_csv(csv_path, index=False)
            return df

        # a plain print() here lands in marimo's console stream, which the
        # read-only `marimo run` app view doesn't display -- mo.output.append()
        # attaches it to the *calling* cell's actual output instead, so it's
        # visible in both edit and run mode
        mo.output.append(
            f"Note: this dataset has {total_count:,} rows, too many to download in "
            f"full here, so a SAMPLE of {max_rows:,} rows is used instead. "
            "This is NOT the complete dataset -- see the data shop link above "
            "if you need everything."
        )

        r = session.get(schema_url)
        r.raise_for_status()
        date_field = next(
            (f["name"] for f in r.json().get("fields", []) if f.get("type") in ("date", "datetime")),
            None,
        )

        # no date field to spread the sample across -- just take the first max_rows
        if date_field is None:
            df = download_csv_page(session, dataset_id, limit=max_rows)
            df.to_csv(csv_path, index=False)
            return df

        import datetime

        def parse_date_str(value):
            # NOT pd.Timestamp/pd.to_datetime: those segfault the whole
            # Python process under Python 3.14 with current pandas versions
            # (confirmed reproducible) -- plain datetime parsing has no such
            # issue, and day-granularity is all the `where` filter below
            # needs anyway
            value = value.split("T")[0]
            parts = value.split("-")
            year = int(parts[0])
            month = int(parts[1]) if len(parts) > 1 else 1
            day = int(parts[2]) if len(parts) > 2 else 1
            return datetime.date(year, month, day)

        r = session.get(
            records_url, params={**common_params, "limit": 1, "order_by": f"{date_field} asc"}
        )
        r.raise_for_status()
        start = parse_date_str(r.json()["results"][0][date_field])
        r = session.get(
            records_url, params={**common_params, "limit": 1, "order_by": f"{date_field} desc"}
        )
        r.raise_for_status()
        end = parse_date_str(r.json()["results"][0][date_field]) + datetime.timedelta(days=1)

        n_windows = 10
        rows_per_window = max_rows // n_windows
        span_days = (end - start).days
        edges = [
            start + datetime.timedelta(days=round(i * span_days / n_windows))
            for i in range(n_windows + 1)
        ]

        dfs: list[pd.DataFrame] = []
        with mo.status.progress_bar(total=n_windows, title=f"Lade Stichprobe von {dataset_id}") as bar:
            for i in range(n_windows):
                lo, hi = edges[i].strftime("%Y-%m-%d"), edges[i + 1].strftime("%Y-%m-%d")
                bar.update(subtitle=f"{lo} bis {hi}")
                where = f"{date_field} >= date'{lo}' and {date_field} < date'{hi}'"
                dfs.append(download_csv_page(session, dataset_id, limit=rows_per_window, where=where))

        df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
        df.to_csv(csv_path, index=False)
        return df
    return (get_dataset,)

@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Load data""")
    return


@app.cell
def _(get_dataset, mo):
    # Read the dataset
    df = get_dataset(dataset_id="100300")
    # mo.output.append() (not a bare trailing `df`) so this stacks below any
    # disclaimer get_dataset() already appended, instead of replacing it
    mo.output.append(df)
    return (df,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Analyze Data""")
    return


@app.cell
def _(df):
    # check missing values with missingno
    # https://github.com/ResidentMario/missingno
    import missingno as msno

    msno.matrix(df, labels=True, sort="descending")
    return


@app.cell
def _(df):
    df.info(memory_usage="deep", verbose=True)
    return


@app.cell
def _(df, pd, plt):
    # plot a histogram for each numerical feature
    try:
        df.hist(bins=25, rwidth=0.9)
        plt.tight_layout()
        hist_output = plt.gcf()
    except ValueError:
        hist_output = "No numerical data to plot."
    hist_output
    return


@app.cell
def _(df):
    # plot geographic points/shapes on a map
    if "geo_shape" in df.columns or "geo_point_2d" in df.columns:
        try:
            import datetime
            import json

            import folium
            from folium.plugins import MarkerCluster, TimestampedGeoJson

            MAX_FEATURES = 5000  # keep the map responsive for datasets with many geo rows
            # shapes (polygons) carry far more coordinate data per feature than
            # points do -- 5000 points stays well under marimo's ~10MB output
            # limit, but 5000 polygons can serialize to 15-20MB and get replaced
            # with a "too large to show" message instead of the map
            MAX_SHAPE_FEATURES = 2000

            def try_parse_date(value):
                # NOT pd.to_datetime: segfaults the whole Python process
                # under Python 3.14 with current pandas versions (confirmed
                # reproducible) -- plain datetime parsing has no such issue
                if not isinstance(value, str):
                    return None
                try:
                    value = value.split("T")[0]
                    parts = value.split("-")
                    return datetime.date(
                        int(parts[0]),
                        int(parts[1]) if len(parts) > 1 else 1,
                        int(parts[2]) if len(parts) > 2 else 1,
                    )
                except (ValueError, IndexError):
                    return None

            has_shapes = "geo_shape" in df.columns and df["geo_shape"].notna().any()

            # look for a usable time column so a dataset with many repeated/
            # overlapping records isn't all shown at once -- instead the map
            # gets a time slider to step/animate through it. Applies whether
            # the dataset has point or shape (polygon) geometry.
            time_col = None
            for col in df.columns:
                if any(k in col.lower() for k in ("zeit", "datum", "date", "time", "jahr")):
                    parsed = df[col].apply(try_parse_date)
                    if parsed.notna().mean() > 0.8:
                        time_col = col
                        break

            if has_shapes:
                # geo_shape holds the real geometry (e.g. polygons); geo_point_2d is
                # often just a simplified representative point of the same feature.
                # A handful of rows in some datasets use GeometryCollection, which
                # nests sub-geometries under "geometries" instead of a direct
                # "coordinates" key -- folium/Leaflet can't render that, so those
                # rows are skipped rather than crashing the whole map.
                if time_col is not None:
                    shape_times = df[time_col].apply(try_parse_date)
                    valid = df[["geo_shape"]].join(shape_times.rename("time")).dropna()
                    if len(valid) > MAX_SHAPE_FEATURES:
                        valid = valid.sample(MAX_SHAPE_FEATURES, random_state=0)
                    features = [
                        {
                            "type": "Feature",
                            "geometry": geometry,
                            "properties": {
                                "times": [row.time.isoformat()],
                                "style": {"color": "#d62728", "fillOpacity": 0.4},
                            },
                        }
                        for row in valid.itertuples()
                        if "coordinates" in (geometry := json.loads(row.geo_shape))
                    ]
                    m = folium.Map()
                    layer = TimestampedGeoJson(
                        {"type": "FeatureCollection", "features": features},
                        period="P1D",
                        duration="P30D",  # rolling window: shapes fade out after 30 days
                        add_last_point=False,
                    )
                    layer.add_to(m)
                    m.fit_bounds(layer.get_bounds())
                else:
                    shapes = df["geo_shape"].dropna()
                    if len(shapes) > MAX_SHAPE_FEATURES:
                        shapes = shapes.sample(MAX_SHAPE_FEATURES, random_state=0)
                    features = [
                        {"type": "Feature", "geometry": geometry, "properties": {}}
                        for shape in shapes
                        if "coordinates" in (geometry := json.loads(shape))
                    ]
                    m = folium.Map()
                    layer = folium.GeoJson({"type": "FeatureCollection", "features": features})
                    layer.add_to(m)
                    m.fit_bounds(layer.get_bounds())
            else:
                geo = df["geo_point_2d"].dropna().str.split(",", expand=True).astype(float)
                geo.columns = ["lat", "lon"]

                if time_col is not None:
                    times = df.loc[geo.index, time_col].apply(try_parse_date)
                    valid = geo.join(times.rename("time")).dropna()
                    if len(valid) > MAX_FEATURES:
                        valid = valid.sample(MAX_FEATURES, random_state=0)
                    features = [
                        {
                            "type": "Feature",
                            "geometry": {"type": "Point", "coordinates": [row.lon, row.lat]},
                            "properties": {
                                "times": [row.time.isoformat()],
                                "icon": "circle",
                                "iconstyle": {
                                    "fillColor": "#d62728",
                                    "fillOpacity": 0.6,
                                    "stroke": False,
                                    "radius": 5,
                                },
                            },
                        }
                        for row in valid.itertuples()
                    ]
                    m = folium.Map(location=[geo["lat"].mean(), geo["lon"].mean()], zoom_start=13)
                    TimestampedGeoJson(
                        {"type": "FeatureCollection", "features": features},
                        period="P1D",
                        duration="P30D",  # rolling window: points fade out after 30 days
                        add_last_point=False,
                    ).add_to(m)
                else:
                    if len(geo) > MAX_FEATURES:
                        geo = geo.sample(MAX_FEATURES, random_state=0)
                    m = folium.Map(location=[geo["lat"].mean(), geo["lon"].mean()], zoom_start=13)
                    cluster = MarkerCluster().add_to(m)
                    for _, row in geo.iterrows():
                        folium.CircleMarker(location=[row["lat"], row["lon"]], radius=4).add_to(cluster)

            geo_output = m
        except (ValueError, AttributeError):
            geo_output = "Could not parse geographic data for plotting."
    else:
        geo_output = "This dataset does not contain geographic data (geo_point_2d/geo_shape)."
    geo_output
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""**Questions about the data?** Open Data Basel-Stadt | opendata@bs.ch""")
    return

if __name__ == "__main__":
    app.run()
