# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo",
#     "matplotlib==3.10.6",
#     "missingno==0.5.2",
#     "pandas==2.3.2",
#     "polars==1.32.3",
#     "requests==2.32.5",
# ]
# ///

import marimo

__generated_with = "0.15.1"
app = marimo.App(auto_download=["html"])


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Open Government Data, provided by **Statistisches Amt des Kantons Basel-Stadt - DCC Data Competence Center**
    *Autogenerated Python starter code for dataset with identifier* **100380**
    """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
    ## Dataset
    # **Entwicklung und Zusammenarbeit: Unterstützte Projekte**
    **Description**: <p>Basel engagiert sich für die Verbesserung der Lebensumstände der Ärmsten dieser Welt. Für Projekte der ausländischen Entwicklungszusammenarbeit stellt der Kanton jährlich 2 Mio. Franken bereit. Mit den finanziellen Beiträgen sollen die Entwicklungschancen der Bevölkerung in den ärmsten Ländern der Welt oder in speziell benachteiligten Regionen nachhaltig verbessert werden. Die Entwicklungszusammenarbeit des Kantons Basel-Stadt engagiert sich ausschliesslich im Rahmen von Projekten im Ausland, wobei thematische Schwerpunkte im Fokus stehen (medizinische Versorgung, Landwirtschaft, Bildung, Gewerbeförderung etc.).</p>
<p>Die <a href="https://www.bs.ch/pd/marketing/eza#kommission" target="_blank">Kommission für Entwicklungszusammenarbeit</a> (<a href="https://www.bs.ch/pd/marketing/eza#kommission" target="_blank">https://www.bs.ch/pd/marketing/eza#kommission</a>) trifft sich zwei Mal jährlich zur Auswahl von Projekten. Bei der Beurteilung von Projektanträgen orientiert sich die Kommission an einem Kriterienkatalog (Qualität, Relevanz, Effektivität, Wirkung, Nachhaltigkeit, Transparenz der Finanzierung, ethische Aspekte). Es wird darauf geachtet, dass bei der Vergabe der Mittel ein gewisser Turnus angewendet wird und Hilfswerke, welche in der Region domiziliert sind, besonders berücksichtigt werden.</p>
<p>Die Regierungsratsbeschlüsse zur Auswahl der zu unterstützenden Projekte werden jeweils veröffentlicht unter: <a href="https://www.bs.ch/apps/regierungsratsbeschluesse" target="_blank">https://www.bs.ch/apps/regierungsratsbeschluesse</a> (Stichwort: Entwicklungszusammenarbeit)</p><p>Änderungsprotokoll:<br>30.9.25: Anpassung Titel und Beschreibung: neu "Entwicklung und Zusammenarbeit" anstelle von "Entwicklungszusammenarbeit"</p>

    *You can find the dataset [under this link](https://data.bs.ch/explore/dataset/100380)*.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Metadata

    - **Dataset_identifier** `100380`
- **Title** `Entwicklung und Zusammenarbeit: Unterstützte Projekte`
- **Description** `<p>Basel engagiert sich für die Verbesserung der Lebensumstände der Ärmsten dieser Welt. Für Projekte der ausländischen Entwicklungszusammenarbeit stellt der Kanton jährlich 2 Mio. Franken bereit. Mit den finanziellen Beiträgen sollen die Entwicklungschancen der Bevölkerung in den ärmsten Ländern der Welt oder in speziell benachteiligten Regionen nachhaltig verbessert werden. Die Entwicklungszusammenarbeit des Kantons Basel-Stadt engagiert sich ausschliesslich im Rahmen von Projekten im Ausland, wobei thematische Schwerpunkte im Fokus stehen (medizinische Versorgung, Landwirtschaft, Bildung, Gewerbeförderung etc.).</p>
<p>Die <a href="https://www.bs.ch/pd/marketing/eza#kommission" target="_blank">Kommission für Entwicklungszusammenarbeit</a> (<a href="https://www.bs.ch/pd/marketing/eza#kommission" target="_blank">https://www.bs.ch/pd/marketing/eza#kommission</a>) trifft sich zwei Mal jährlich zur Auswahl von Projekten. Bei der Beurteilung von Projektanträgen orientiert sich die Kommission an einem Kriterienkatalog (Qualität, Relevanz, Effektivität, Wirkung, Nachhaltigkeit, Transparenz der Finanzierung, ethische Aspekte). Es wird darauf geachtet, dass bei der Vergabe der Mittel ein gewisser Turnus angewendet wird und Hilfswerke, welche in der Region domiziliert sind, besonders berücksichtigt werden.</p>
<p>Die Regierungsratsbeschlüsse zur Auswahl der zu unterstützenden Projekte werden jeweils veröffentlicht unter: <a href="https://www.bs.ch/apps/regierungsratsbeschluesse" target="_blank">https://www.bs.ch/apps/regierungsratsbeschluesse</a> (Stichwort: Entwicklungszusammenarbeit)</p><p>Änderungsprotokoll:<br>30.9.25: Anpassung Titel und Beschreibung: neu "Entwicklung und Zusammenarbeit" anstelle von "Entwicklungszusammenarbeit"</p>`
- **Contact_name** `Open Data Basel-Stadt`
- **Issued** `2024-08-09`
- **Modified** `2025-04-28T07:48:11+00:00`
- **Rights** `NonCommercialAllowed-CommercialAllowed-ReferenceRequired`
- **Temporal_coverage_start_date** `2019-12-31T23:00:00+00:00`
- **Temporal_coverage_end_date** `2024-12-30T23:00:00+00:00`
- **Themes** `['Politik']`
- **Keywords** `['Entwicklung', 'Entwicklungszusammenarbeit', 'Projekte', 'Engagement', 'Ausland', 'international', 'Medizin', 'Bildung', 'Landwirtschaft', 'Gewerbeförderung', 'Hilfswerk']`
- **Publisher** `Aussenbeziehungen und Standortmarketing`
- **Reference** `None`


    ///
    """
    )
    return


@app.cell
def _():
    import os
    import pandas as pd
    import requests
    import matplotlib.pyplot as plt
    return os, pd, plt, requests


@app.cell
def _(plt):
    plt.style.use("ggplot")

    params = {
        "text.color": (0.25, 0.25, 0.25),
        "figure.figsize": [18, 6],
    }

    plt.rcParams.update(params)
    return


@app.cell
def _(os, pd, requests):
    def get_dataset(dataset_id):
        url = f"https://data.bs.ch/api/explore/v2.1/catalog/datasets/{dataset_id}/exports/csv"
        r = requests.get(
            url, 
            params={
                "timezone": "Europe%2FZurich",
                "use_labels": "true"
            }
        )
        data_path = os.path.join(os.getcwd(), "..", "data")
        if not os.path.exists(data_path):
            os.makedirs(data_path)
        csv_path = os.path.join(data_path, f"{dataset_id}.csv")
        with open(csv_path, "wb") as f:
            f.write(r.content)
        data = pd.read_csv(
            url, sep=";", on_bad_lines="warn", encoding_errors="ignore", low_memory=False
        )
        # if dataframe only has one column or less the data is not ";" separated
        if data.shape[1] <= 1:
            print(
                "The data wasn't imported properly. Very likely the correct separator couldn't be found.\nPlease check the dataset manually and adjust the code."
            )
        return data
    return (get_dataset,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Load data""")
    return


@app.cell
def _(get_dataset):
    # Read the dataset
    df = get_dataset(dataset_id="100380")
    df
    return (df,)


@app.cell
def _(mo):
    mo.md(r"""## Analyze Data""")
    return


@app.cell
def _(df):
    # check missing values with missingno
    # https://github.com/ResidentMario/missingno
    import missingno as msno

    msno.matrix(df, labels=True, sort="descending")
    return


@app.cell
def _(df):
    df.info(memory_usage="deep", verbose=True)
    return


@app.cell
def _(df, pd, plt):
    # plot a histogram for each numerical feature
    try:
        df.hist(bins=25, rwidth=0.9)
        plt.tight_layout()
        plt.show()
    except pd.errors.DataError:
        print("No numerical data to plot.")
    return

@app.cell
def _(mo):
    mo.md(r"""**Questions about the data?** Open Data Basel-Stadt | opendata@bs.ch""")
    return

if __name__ == "__main__":
    app.run()
