# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo",
#     "matplotlib==3.10.6",
#     "missingno==0.5.2",
#     "pandas==2.3.2",
#     "polars==1.32.3",
#     "requests==2.32.5",
# ]
# ///

import marimo

__generated_with = "0.15.1"
app = marimo.App(auto_download=["html"])


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Open Government Data, provided by **Statistisches Amt des Kantons Basel-Stadt - DCC Data Competence Center**
    *Autogenerated Python starter code for dataset with identifier* **100408**
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Dataset
    # **Veränderte Wahlzettel der Grossratswahlen 20. Oktober 2024**
    **Description**: <p>Bei den Grossratswahlen im Kanton Basel-Stadt am 20. Oktober 2024 kandidierten 870 Personen (verfügbar unter <a href="https://data.bs.ch/explore/dataset/100385/" target="_blank">https://data.bs.ch/explore/dataset/100385/</a>) für insgesamt 100 zu vergebende Sitze.</p><p> Es gingen insgesamt 42 640 gültige Wahlzettel ein, von denen 20 733 verändert wurden. Der Datensatz zeigt diese 20 733 Wahlzettel und jegliche Details dazu. </p><p>Leere Felder bei der Stimme bedeuten, dass das Feld leer gelassen wurde. Felder mit NULL bei der Stimme bedeuten, dass in diesem Wahlkreis weniger Stimmen zur Verfügung standen.</p><p>Die Listennummer 00 bedeutet, dass ein Wahlzettel ohne Bezeichnung ausgefüllt wurde (insgesamt 3 326 Wahlzettel). In diesem Fall werden leere Stimmen nicht gezählt.</p><p>Es gibt zwei Arten wie man einen Wahlzettel verändern kann: <br>Panaschieren bedeutet, dass Kandidierende von anderen Listen auf die ausgewählte Liste übertragen wurden. <br>Kumulieren bezeichnet das Mehrfachnennen eines Kandidierenden, wodurch diese mehr als eine Stimme erhält. <br>Im Datensatz wird "p" für panaschiert und "k" für kumuliert verwendet. Wenn ein Wahlzettel sowohl panaschiert als auch kumuliert wurde, wird ebenfalls "p" ausgewiesen. </p><p><span>Die Wahlergebnisse sind in einem separaten Datensatz (</span><a 255);"="" 255,="" background-color:="" href="https://data.bs.ch/explore/dataset/100399/" rgb(255,="" target="_blank">https://data.bs.ch/explore/dataset/100399/</a><span>) einsehbar, der die Verteilung der Stimmen und die gewählten Vertreter detailliert darstellt.</span></p>

    *You can find the dataset [under this link](https://data.bs.ch/explore/dataset/100408)*.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Metadata

- **Dataset_identifier** `100408`
- **Title** `Veränderte Wahlzettel der Grossratswahlen 20. Oktober 2024`
- **Description** `<p>Bei den Grossratswahlen im Kanton Basel-Stadt am 20. Oktober 2024 kandidierten 870 Personen (verfügbar unter <a href="https://data.bs.ch/explore/dataset/100385/" target="_blank">https://data.bs.ch/explore/dataset/100385/</a>) für insgesamt 100 zu vergebende Sitze.</p><p> Es gingen insgesamt 42 640 gültige Wahlzettel ein, von denen 20 733 verändert wurden. Der Datensatz zeigt diese 20 733 Wahlzettel und jegliche Details dazu. </p><p>Leere Felder bei der Stimme bedeuten, dass das Feld leer gelassen wurde. Felder mit NULL bei der Stimme bedeuten, dass in diesem Wahlkreis weniger Stimmen zur Verfügung standen.</p><p>Die Listennummer 00 bedeutet, dass ein Wahlzettel ohne Bezeichnung ausgefüllt wurde (insgesamt 3 326 Wahlzettel). In diesem Fall werden leere Stimmen nicht gezählt.</p><p>Es gibt zwei Arten wie man einen Wahlzettel verändern kann: <br>Panaschieren bedeutet, dass Kandidierende von anderen Listen auf die ausgewählte Liste übertragen wurden. <br>Kumulieren bezeichnet das Mehrfachnennen eines Kandidierenden, wodurch diese mehr als eine Stimme erhält. <br>Im Datensatz wird "p" für panaschiert und "k" für kumuliert verwendet. Wenn ein Wahlzettel sowohl panaschiert als auch kumuliert wurde, wird ebenfalls "p" ausgewiesen. </p><p><span>Die Wahlergebnisse sind in einem separaten Datensatz (</span><a 255);"="" 255,="" background-color:="" href="https://data.bs.ch/explore/dataset/100399/" rgb(255,="" target="_blank">https://data.bs.ch/explore/dataset/100399/</a><span>) einsehbar, der die Verteilung der Stimmen und die gewählten Vertreter detailliert darstellt.</span></p>`
- **Contact_name** `Open Data Basel-Stadt`
- **Issued** `2024-12-06`
- **Modified** `2026-03-16T11:42:33+00:00`
- **Rights** `NonCommercialAllowed-CommercialAllowed-ReferenceRequired`
- **Temporal_coverage_start_date** `None`
- **Temporal_coverage_end_date** `None`
- **Themes** `['Politik', 'Bevölkerung']`
- **Keywords** `['Wahlen', 'Abstimmung', 'Demokratie', 'Teilhabe', 'Parlament', 'Grosser Rat', 'Grossrat', 'Grossrätin']`
- **Creator** `Staatskanzlei`
- **Reference** `None`


    ///
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Data dictionary

| Field | Type | Description |
| :-- | :-- | :-- |
| `wahljahr` | text | Wahljahr |
| `wahlkreis` | text | Wahlkreis |
| `anzahl_sitze` | int | Anzahl Sitze für Wahlkreis |
| `listen_nr` | text | Listennummer |
| `listenkurzbezeichnung` | text | Listenkurzbezeichnung |
| `listenbezeichnung` | text | Listenbezeichnung |
| `wahlzettel_id` | text | Eindeutiger Identifikator des Wahlzettels |
| `wahlzettel_typ` | text | p = panaschiert; k = kumuliert |
| `kandidat_01` | text | Kandidierenden Nr. der ersten Stimme |
| `kandidat_01_name` | text | Ganzer Name der ersten Stimme |
| `kandidat_02` | text | Kandidierenden Nr. der zweiten Stimme |
| `kandidat_02_name` | text | Ganzer Name der zweiten Stimme |
| `kandidat_03` | text | Kandidierenden Nr. der dritten Stimme |
| `kandidat_03_name` | text | Ganzer Name der dritten Stimme |
| `kandidat_04` | text | Kandidierenden Nr. der vierten Stimme |
| `kandidat_04_name` | text | Ganzer Name der vierten Stimme |
| `kandidat_05` | text | Kandidierenden Nr. der fünften Stimme |
| `kandidat_05_name` | text | Ganzer Name der fünften Stimme |
| `kandidat_06` | text | Kandidierenden Nr. der sechsten Stimme |
| `kandidat_06_name` | text | Ganzer Name der sechsten Stimme |
| `kandidat_07` | text | Kandidierenden Nr. der siebten Stimme |
| `kandidat_07_name` | text | Ganzer Name der siebten Stimme |
| `kandidat_08` | text | Kandidierenden Nr. der achten Stimme |
| `kandidat_08_name` | text | Ganzer Name der achten Stimme |
| `kandidat_09` | text | Kandidierenden Nr. der neunten Stimme |
| `kandidat_09_name` | text | Ganzer Name der neunten Stimme |
| `kandidat_10` | text | Kandidierenden Nr. der zehnten Stimme |
| `kandidat_10_name` | text | Ganzer Name der zehnten Stimme |
| `kandidat_11` | text | Kandidierenden Nr. der elften Stimme |
| `kandidat_11_name` | text | Ganzer Name der elften Stimme |
| `kandidat_12` | text | Kandidierenden Nr. der zwölften Stimme |
| `kandidat_12_name` | text | Ganzer Name der zwölften Stimme |
| `kandidat_13` | text | Kandidierenden Nr. der 13. Stimme |
| `kandidat_13_name` | text | Ganzer Name der 13. Stimme |
| `kandidat_14` | text | Kandidierenden Nr. der 14. Stimme |
| `kandidat_14_name` | text | Ganzer Name der 14. Stimme |
| `kandidat_15` | text | Kandidierenden Nr. der 15. Stimme |
| `kandidat_15_name` | text | Ganzer Name der 15. Stimme |
| `kandidat_16` | text | Kandidierenden Nr. der 16. Stimme |
| `kandidat_16_name` | text | Ganzer Name der 16. Stimme |
| `kandidat_17` | text | Kandidierenden Nr. der 17. Stimme |
| `kandidat_17_name` | text | Ganzer Name der 17. Stimme |
| `kandidat_18` | text | Kandidierenden Nr. der 18. Stimme |
| `kandidat_18_name` | text | Ganzer Name der 18. Stimme |
| `kandidat_19` | text | Kandidierenden Nr. der 19. Stimme |
| `kandidat_19_name` | text | Ganzer Name der 19. Stimme |
| `kandidat_20` | text | Kandidierenden Nr. der 20. Stimme |
| `kandidat_20_name` | text | Ganzer Name der 20. Stimme |
| `kandidat_21` | text | Kandidierenden Nr. der 21. Stimme |
| `kandidat_21_name` | text | Ganzer Name der 21. Stimme |
| `kandidat_22` | text | Kandidierenden Nr. der 22. Stimme |
| `kandidat_22_name` | text | Ganzer Name der 22. Stimme |
| `kandidat_23` | text | Kandidierenden Nr. der 23. Stimme |
| `kandidat_23_name` | text | Ganzer Name der 23. Stimme |
| `kandidat_24` | text | Kandidierenden Nr. der 24. Stimme |
| `kandidat_24_name` | text | Ganzer Name der 24. Stimme |
| `kandidat_25` | text | Kandidierenden Nr. der 25. Stimme |
| `kandidat_25_name` | text | Ganzer Name der 25. Stimme |
| `kandidat_26` | text | Kandidierenden Nr. der 26. Stimme |
| `kandidat_26_name` | text | Ganzer Name der 26. Stimme |
| `kandidat_27` | text | Kandidierenden Nr. der 27. Stimme |
| `kandidat_27_name` | text | Ganzer Name der 27. Stimme |
| `kandidat_28` | text | Kandidierenden Nr. der 28. Stimme |
| `kandidat_28_name` | text | Ganzer Name der 28. Stimme |
| `kandidat_29` | text | Kandidierenden Nr. der 29. Stimme |
| `kandidat_29_name` | text | Ganzer Name der 29. Stimme |
| `kandidat_30` | text | Kandidierenden Nr. der 30. Stimme |
| `kandidat_30_name` | text | Ganzer Name der 30. Stimme |
| `kandidat_31` | text | Kandidierenden Nr. der 31. Stimme |
| `kandidat_31_name` | text | Ganzer Name der 31. Stimme |
| `kandidat_32` | text | Kandidierenden Nr. der 32. Stimme |
| `kandidat_32_name` | text | Ganzer Name der 32. Stimme |
| `kandidat_33` | text | Kandidierenden Nr. der 33. Stimme |
| `kandidat_33_name` | text | Ganzer Name der 33. Stimme |
| `kandidat_34` | text | Kandidierenden Nr. der 34. Stimme |
| `kandidat_34_name` | text | Ganzer Name der 34. Stimme |


    ///
    """
    )
    return


@app.cell
def _():
    import os
    import io
    import pandas as pd
    import requests
    import matplotlib.pyplot as plt
    return os, io, pd, plt, requests


@app.cell
def _(plt):
    plt.style.use("ggplot")

    params = {
        "text.color": (0.25, 0.25, 0.25),
        "figure.figsize": [18, 6],
    }

    plt.rcParams.update(params)
    return


@app.cell
def _(os):
    def ensure_data_dir() -> str:
        data_path = os.path.join(os.getcwd(), "..", "data")
        os.makedirs(data_path, exist_ok=True)
        return data_path
    return (ensure_data_dir,)


@app.cell
def _(io, pd, requests):
    def download_csv_chunk(
        session: requests.Session,
        dataset_id: str,
        extra_params: dict | None = None,
    ) -> pd.DataFrame:
        base_url = "https://data.bs.ch/api/explore/v2.1"
        url = f"{base_url}/catalog/datasets/{dataset_id}/exports/csv"

        params = {
            "timezone": "Europe/Zurich",
            "use_labels": "false",
        }
        if extra_params:
            params.update(extra_params)

        r = session.get(url, params=params)
        r.raise_for_status()

        buf = io.BytesIO(r.content)

        df = pd.read_csv(
            buf,
            sep=";",
            on_bad_lines="warn",
            encoding_errors="ignore",
            low_memory=False,
        )

        return df
    return (download_csv_chunk,)


@app.cell
def _():
    def pick_best_facet(facets_json: dict, max_rows_per_chunk: int) -> tuple[str | None, list[str]]:
        """
        Choose a facet column where each bucket has <= max_rows_per_chunk rows.
        Among all such columns, pick the one with the smallest worst-case bucket.
        Returns (facet_name, list_of_values) or (None, []) if nothing suitable.
        """
        best_name = None
        best_values: list[str] = []
        best_max_bucket = None

        for facet in facets_json.get("facets", []):
            facet_name = facet.get("name")
            value_list = facet.get("facets", [])
            if not facet_name or not value_list:
                continue

            counts = [v.get("count", 0) for v in value_list]
            if not counts:
                continue

            max_bucket = max(counts)
            if max_bucket > max_rows_per_chunk:
                # this facet would still exceed the chunk limit for some values
                continue

            if best_max_bucket is None or max_bucket < best_max_bucket:
                best_max_bucket = max_bucket
                best_name = facet_name
                best_values = [v.get("value") for v in value_list if v.get("value") is not None]

        return best_name, best_values


@app.cell
def _(download_csv_chunk, ensure_data_dir, mo, os, pd, requests):
    def get_dataset(dataset_id: str, max_rows_per_chunk: int = 50_000) -> pd.DataFrame:
        """
        Download a dataset from data.bs.ch.

        - For small datasets (<= max_rows_per_chunk): single CSV export.
        - For large datasets:
            * Inspect /facets to find a good splitting column.
            * Download one CSV per facet value via refine.<col>=<value>.
            * Additionally download rows where that column is NULL via q=#null(<col>).

        The combined result is written to ../data/{dataset_id}.csv and returned as a DataFrame.
        """
        base_url = "https://data.bs.ch/api/explore/v2.1"
        records_url = f"{base_url}/catalog/datasets/{dataset_id}/records"
        facets_url = f"{base_url}/catalog/datasets/{dataset_id}/facets"

        session = requests.Session()
        common_params = {
            "timezone": "Europe/Zurich",
            "use_labels": "false",
        }

        # 1) Get total_count via /records
        r = session.get(records_url, params={**common_params, "limit": 1})
        r.raise_for_status()
        meta = r.json()
        total_count = meta.get("total_count", 0)

        if not isinstance(total_count, int):
            # fall back to simple export if we can't read total_count
            total_count = 0

        # 2) Small dataset: single CSV export
        if total_count == 0 or total_count <= max_rows_per_chunk:
            df = download_csv_chunk(session, dataset_id, extra_params={})
            data_path = ensure_data_dir()
            csv_path = os.path.join(data_path, f"{dataset_id}.csv")
            df.to_csv(csv_path, index=False)
            return df

        # 3) Large dataset: inspect /facets to decide how to split
        r = session.get(facets_url, params=common_params)
        r.raise_for_status()
        facets_json = r.json()

        facet_name, facet_values = pick_best_facet(facets_json, max_rows_per_chunk=max_rows_per_chunk)

        if facet_name is None or not facet_values:
            raise RuntimeError(
                f"Could not find a facet column to split dataset {dataset_id} into "
                f"chunks of <= {max_rows_per_chunk} rows. Please handle this dataset manually."
            )

        dfs: list[pd.DataFrame] = []

        # 4) Download each facet value (refine.<facet_name>=value)
        n_parts = len(facet_values) + 1  # +1 for NULLs

        with mo.status.progress_bar(
            total=n_parts,
            title=f"Lade Datensatz {dataset_id}",
            subtitle=f"Split nach '{facet_name}'…",
        ) as bar:
            # NULLs
            bar.update(subtitle=f"{facet_name} = NULL")
            null_query = {"qv1": f"#null({facet_name})"}
            try:
                df_null = download_csv_chunk(session, dataset_id, extra_params=null_query)
                if not df_null.empty:
                    dfs.append(df_null)
            except requests.HTTPError as e:
                print(f"Warning: NULL download for {facet_name} failed: {e}")
            # non-NULL values
            for v in facet_values:
                bar.update(subtitle=f"{facet_name} = {v!r}")
                params = {"refine": f'{facet_name}:"{v}"'}
                df_chunk = download_csv_chunk(session, dataset_id, extra_params=params)
                dfs.append(df_chunk)

        # 5) Combine all parts, save to a single CSV, return DataFrame
        if dfs:
            full_df = pd.concat(dfs, ignore_index=True)
        else:
            full_df = pd.DataFrame()

        data_path = ensure_data_dir()
        csv_path = os.path.join(data_path, f"{dataset_id}.csv")
        full_df.to_csv(csv_path, index=False)

        return full_df
    return (get_dataset,)

@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Load data""")
    return


@app.cell
def _(get_dataset):
    # Read the dataset
    df = get_dataset(dataset_id="100408")
    df
    return (df,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Analyze Data""")
    return


@app.cell
def _(df):
    # check missing values with missingno
    # https://github.com/ResidentMario/missingno
    import missingno as msno

    msno.matrix(df, labels=True, sort="descending")
    return


@app.cell
def _(df):
    df.info(memory_usage="deep", verbose=True)
    return


@app.cell
def _(df, pd, plt):
    # plot a histogram for each numerical feature
    try:
        df.hist(bins=25, rwidth=0.9)
        plt.tight_layout()
        plt.show()
    except ValueError:
        print("No numerical data to plot.")
    return

@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""**Questions about the data?** Open Data Basel-Stadt | opendata@bs.ch""")
    return

if __name__ == "__main__":
    app.run()
